### PR TITLE
Handle anonymous classes more gracefully

### LINKED ISSUE #24: Registry::getManagerForClass doesn't work with anonymous classes
### Situation:

* PHP 7.1.5
* Using windows (it's an important part)
* Trying to use Symfony validator to validate anonymous class

The validator point is useless, but what's triggered behind is the<br>`$registry->getManagerForClass(get_class($myAnonymousClassInstance));`

### The test

```php
$a = new class {
    public $value;
};

var_dump(get_class($a));

$manager = $this->getDoctrine()->getManagerForClass(get_class($a));
```` 

Output on Windows:

`class@anonymous\x00E:\dev\www\skeleton\src\AppBundle\Controller\DefaultController.php000001982329027F` 

With this, I get an `ORMException`:

```
Unknown Entity namespace alias 'class@anonymousE'.
```

Obviously, because there is the `:` syntax, Doctrine is looking for a specific entity namespace.

---

I also tested this on linux inside a command and it works:

```php
$a = new class {
    public $value;
};

$manager = $this->getContainer()->get('doctrine')->getManagerForClass(get_class($a));

var_dump($class, $manager);
```

Output is correct because `$manager` is `null`:

```
"class@anonymous\x00/mnt/e/dev/www/skeleton/src/AppBundle/Command/TestCommand.php0x7f66b1aa5341"
null
```

### The fix

I think the `AbstractManagerRegistry::getManagerForClass()` should return `null` if the class name starts with `class@anonymous\x00`, whatever the platform, because it is the way PHP 7.1 handles anonymous classes names.

What do you think?

### PR DESCRIPTION
**Pull request by greg0ire**
Fixes #24

### CODE REVIEW

**Comment by stof** [comment]
I think you also need to update `isTransient`, to avoid making it trigger a deprecation and call `getFqcnFromAlias` if the anonymous class name contains a `:`.

File: src/Persistence/Mapping/AbstractClassMetadataFactory.php [hunk 1]
```diff
@@ -462,7 +468,7 @@ public function isTransient($className)
         }
 
         // Check for namespace alias
-        if (strpos($className, ':') !== false) {
+        if (! class_exists($className) && strpos($className, ':') !== false) {
```
Comment (stof) [inline src/Persistence/Mapping/AbstractClassMetadataFactory.php]: I would use `! class_exists($className, false)`, to avoid triggering autoloaders for namespace aliases. Excluding anonymous classes does not need to trigger the autoloader.

Comment (stof) [reply src/Persistence/Mapping/AbstractClassMetadataFactory.php]: btw, other `class_exists` checks added in the PR in the anonymous class checks should probably do the same, as they are added *before* the resolution of the real class name which resolves aliases.

Comment (greg0ire) [reply src/Persistence/Mapping/AbstractClassMetadataFactory.php]: I think that makes sense, since we want to test if the class is anonymous and anonymous classes surely don't require any autoloading.

File: src/Persistence/Mapping/AbstractClassMetadataFactory.php [hunk 2]
```diff
@@ -220,6 +222,10 @@ abstract protected function isEntity(ClassMetadata $class);
      */
     public function getMetadataFor($className)
     {
+        if (class_exists($className, false) && (new ReflectionClass($className))->isAnonymous()) {
```
Comment (stof) [inline src/Persistence/Mapping/AbstractClassMetadataFactory.php]: should we put that after the check of the cache, to avoid paying the cost of this reflection check when retrieving metadata that was already loaded (which is something that the ORM does a lot, including in its critical path) ?

Comment (greg0ire) [reply src/Persistence/Mapping/AbstractClassMetadataFactory.php]: Sure 👍

**Review by stof — APPROVED** [review]
